os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -project CITest.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.1,name=iPhone 8"